name: Tests

on:
    push:
        branches:
            - '**'

    pull_request:
        branches:
            - '**'

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Specify as per the service requirements
                node-version: [ 14.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm install
            -   run: npm run build --if-present
            -   run: npm test
